// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGltDoxrructPXmWO1XnGUvZWU1d0GEp4',
    appId: '1:688905433463:web:655375a9f25813c4b0b172',
    messagingSenderId: '688905433463',
    projectId: 'flutter-push-f0953',
    authDomain: 'flutter-push-f0953.firebaseapp.com',
    storageBucket: 'flutter-push-f0953.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_wvmu7COTTbWFX4CUB42CHyYKWNpQ0Ho',
    appId: '1:688905433463:android:b882e97dee63f8a2b0b172',
    messagingSenderId: '688905433463',
    projectId: 'flutter-push-f0953',
    storageBucket: 'flutter-push-f0953.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrMP2YvOYviG6791D-wosSx_KtqM3r0kc',
    appId: '1:688905433463:ios:25a5ae6898730b1cb0b172',
    messagingSenderId: '688905433463',
    projectId: 'flutter-push-f0953',
    storageBucket: 'flutter-push-f0953.appspot.com',
    iosBundleId: 'com.example.flutterCafeAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrMP2YvOYviG6791D-wosSx_KtqM3r0kc',
    appId: '1:688905433463:ios:93339d78c2023353b0b172',
    messagingSenderId: '688905433463',
    projectId: 'flutter-push-f0953',
    storageBucket: 'flutter-push-f0953.appspot.com',
    iosBundleId: 'com.example.flutterCafeAdmin.RunnerTests',
  );
}
